const invoiceComponents = [
  { name: 'id', type: 'uint256' },
  { name: 'buyer', type: 'address' },
  { name: 'supplier', type: 'address' },
  { name: 'payoutAddress', type: 'address' },
  { name: 'fullAmount', type: 'uint256' },
  { name: 'earlySettlementAmount', type: 'uint256' },
  { name: 'dueDate', type: 'uint64' },
  { name: 'createdAt', type: 'uint64' },
  { name: 'fundedAt', type: 'uint64' },
  { name: 'settledAt', type: 'uint64' },
  { name: 'invoiceReferenceHash', type: 'bytes32' },
  { name: 'descriptionHash', type: 'bytes32' },
  { name: 'status', type: 'uint8' },
  { name: 'dynamicEarlySettlement', type: 'bool' },
] as const;

const invoiceInputs = [
  { name: 'supplier', type: 'address' },
  { name: 'fullAmount', type: 'uint256' },
  { name: 'earlySettlementAmount', type: 'uint256' },
  { name: 'dueDate', type: 'uint64' },
  { name: 'invoiceReferenceHash', type: 'bytes32' },
  { name: 'descriptionHash', type: 'bytes32' },
] as const;

export const accordPayAbi = [
  {
    type: 'constructor',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_settlementToken', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createInvoice',
    stateMutability: 'nonpayable',
    inputs: invoiceInputs,
    outputs: [{ name: 'invoiceId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createAndFundInvoice',
    stateMutability: 'nonpayable',
    inputs: invoiceInputs,
    outputs: [{ name: 'invoiceId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createDynamicInvoice',
    stateMutability: 'nonpayable',
    inputs: invoiceInputs,
    outputs: [{ name: 'invoiceId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createAndFundDynamicInvoice',
    stateMutability: 'nonpayable',
    inputs: invoiceInputs,
    outputs: [{ name: 'invoiceId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'fundInvoice',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelInvoice',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'rejectInvoice',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'updatePayoutAddress',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }, { name: 'payoutAddress', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleEarly',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'settleAtMaturity',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getInvoice',
    stateMutability: 'view',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [{ name: '', type: 'tuple', components: invoiceComponents }],
  },
  {
    type: 'function',
    name: 'previewEarlySettlement',
    stateMutability: 'view',
    inputs: [{ name: 'invoiceId', type: 'uint256' }],
    outputs: [{ name: 'supplierPayout', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getInvoiceIdsByBuyer',
    stateMutability: 'view',
    inputs: [{ name: 'buyer', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getInvoiceIdsBySupplier',
    stateMutability: 'view',
    inputs: [{ name: 'supplier', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'getInvoiceCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getSettlementToken',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'event',
    name: 'InvoiceCreated',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'supplier', type: 'address', indexed: true },
      { name: 'fullAmount', type: 'uint256', indexed: false },
      { name: 'earlySettlementAmount', type: 'uint256', indexed: false },
      { name: 'dueDate', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InvoiceFunded',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InvoiceCancelled',
    anonymous: false,
    inputs: [{ name: 'id', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'InvoiceRejected',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'supplier', type: 'address', indexed: true },
      { name: 'returnedToBuyer', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PayoutAddressUpdated',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'supplier', type: 'address', indexed: true },
      { name: 'payoutAddress', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'InvoiceSettledEarly',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'payoutAddress', type: 'address', indexed: true },
      { name: 'paidToSupplier', type: 'uint256', indexed: false },
      { name: 'returnedToBuyer', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'InvoiceSettledAtMaturity',
    anonymous: false,
    inputs: [
      { name: 'id', type: 'uint256', indexed: true },
      { name: 'payoutAddress', type: 'address', indexed: true },
      { name: 'triggeredBy', type: 'address', indexed: true },
      { name: 'paidToSupplier', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint64', indexed: false },
    ],
  },
] as const;
